### ISSUE TITLE
Uncaught mysqli_sql_exception: You have an error in your SQL syntax; wp-includes\wp-db.php:2056 Stack

### ISSUE THREAD

**Issue by courtens** [pojome/activity-log#153]
Is this a plugin issue or a database connection issue? I am using php 8.1 
_(I am still trying to find a way to get what was sent to MariaDB.)_

````
Fatal error: 
Uncaught mysqli_sql_exception: You have an error in your SQL syntax; 
check the manual that corresponds to your MariaDB server version for the right syntax 
to use near 'IF' at line 1 in c:\www\wordpress\wp-includes\wp-db.php:2056 Stack 
trace: 
 #0 c:\www\wordpress\wp-includes\wp-db.php(2056): mysqli_query() 
 #1 c:\www\wordpress\wp-includes\wp-db.php(1945): wpdb->_do_query() 
 #2 c:\www\wordpress\wp-includes\wp-db.php(2695): wpdb->query() 
 #3 c:\www\wordpress\wp-admin\includes\upgrade.php(2749): wpdb->get_results() 
 #4 c:\www\wordpress\wp-content\plugins\aryo-activity-log\classes\class-aal-maintenance.php(68): dbDelta() 
 #5 c:\www\wordpress\wp-content\plugins\aryo-activity-log\classes\class-aal-maintenance.php(17): AAL_Maintenance::_create_tables() 
 #6 c:\www\wordpress\wp-includes\class-wp-hook.php(303): AAL_Maintenance::activate() 
 #7 c:\www\wordpress\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters() 
 #8 c:\www\wordpress\wp-includes\plugin.php(470): WP_Hook->do_action() 
 #9 c:\www\wordpress\wp-admin\plugins.php(193): do_action() 
 #10 {main} thrown in  c:\www\wordpress\wp-includes\wp-db.php on line 2056
````

**Comment by arielk** [comment]
I'm closing an issue due to inactivity. If the problem still exists feel free to reopen the issue. 

Thanks!
